version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12.0-stretch
      - image: redis
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn mock-db
      - run: yarn test
      - run: sudo apt-get update
      - run: sudo apt install -y rsync
      - run: if [ "${CIRCLE_BRANCH}" == "circleci" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git*' ./ ubuntu@35.162.65.198:/var/www/chatbot/hopelab_ayachatbot/; fi
      - run: if [ "${CIRCLE_BRANCH}" == "staging" ]; then rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git*' ./ ubuntu@34.212.32.132:/var/www/chatbot/hopelab_ayachatbot/; fi
      - run: if [ "${CIRCLE_BRANCH}" == "circleci" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then ssh -o StrictHostKeyChecking=no ubuntu@35.162.65.198 'cd /var/www/chatbot/hopelab_ayachatbot/ && yarn install && pm2 restart index'; fi
      - run: if [ "${CIRCLE_BRANCH}" == "staging" ]; then ssh -o StrictHostKeyChecking=no ubuntu@34.212.32.132 'cd /var/www/chatbot/hopelab_ayachatbot/ && yarn install && pm2 restart index'; fi
      - run: echo "done!"
