version: 2
jobs:
  test:
    docker:
      - image: circleci/node:6.10
    dependencies:
      override:
        - yarn
      cache_directories:
        - ~/.cache/yarn
    steps:
      - test
      - run: yarn test
  deploy:
    requires:
      - test
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: sudo apt install -y rsync
      - run: if [ "${CIRCLE_BRANCH}" == "circleci" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git*' ./ ubuntu@35.162.65.198:/var/www/chatbot/hopelab_ayachatbot/; fi
      - run: ssh -o StrictHostKeyChecking=no ubuntu@35.162.65.198 'cd /var/www/chatbot/hopelab_ayachatbot/ && yarn install && pm2 restart index'
      - run: echo "done!"
