version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: sudo apt-get update
      - run: sudo apt install -y rsync
      - run: if [ "${CIRCLE_BRANCH}" == "circleci" ] || [ "${CIRCLE_BRANCH}" == "master" ]; then rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git*' ./ ubuntu@35.162.65.198:/var/www/chatbot/hopelab_ayachatbot/; fi
      - run: if [ "${CIRCLE_BRANCH}" == "staging" ]; then rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git*' ./ ubuntu@54.185.52.189:/var/www/chatbot/hopelab_ayachatbot/; fi
      - run: ssh -o StrictHostKeyChecking=no ubuntu@54.185.52.189 'cd /var/www/chatbot/hopelab_ayachatbot/ && yarn install && pm2 restart index'
      - run: echo "done!"
